### PR TITLE
Spell check on article

### PR DESCRIPTION
**Pull request by ali-ahsan-ali**
systme -> system

### CODE REVIEW

**Comment by Joannis** [comment]
Hey @ali-ahsan-ali , thank you for your PR! We're rendering the HTML based on markdown. Could you make the proposed changes inside the markdown file in the same directory? The reason we commit the HTML artifacts is because those are used by github pages

**Comment by Joannis** [comment]
I've applied the fix in #45 as well now

**Comment by Joannis** [comment]
Thanks for bringing it up and the PR :)

**Comment by ali-ahsan-ali** [comment]
Nice, sorry I didn't follow through with this

**Pull request closed without merging**
